
CREATE Schema Contents;
GO 

CREATE Schema Properties;
GO
 
CREATE TABLE Contents.tblAlbums (
	albumID INT IDENTITY(1,1) NOT NULL,
	albumName VARCHAR(255) NOT NULL,
	genreName VARCHAR(255) NOT NULL,
	dateOfRelease DATE NOT NULL,
	FOREIGN KEY (formatID) REFERENCES Contents.tblFormat (formatID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (artistID) REFERENCES Properties.tblArtists (artistID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (bandID) REFERENCES Contents.tblBands (bandID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (roomID) REFERENCES Properties.tblStorageRoom (roomID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (shelfTag) REFERENCES Properties.tblShelf (shelfTag) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (shelfRow) REFERENCES Properties.tblShelfRow (shelfRow) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE Contents.tblArtists (
	artistID INT IDENTITY(1,1) PRIMARY KEY,
	artistName VARCHAR(255) NOT NULL
);

CREATE TABLE Contents.tblBands (
	bandID INT IDENTITY(1,1) PRIMARY KEY,
	bandName VARCHAR(255) NOT NULL
);

CREATE TABLE Properties.tblFormat (
	formatID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	formatName VARCHAR(10) NOT NULL
);

CREATE TABLE Properties.tblStorageRoom (
	roomID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	roomName VARCHAR(20) NOT NULL
);

CREATE TABLE Properties.tblShelf (
	shelfTag VARCHAR(1) PRIMARY KEY NOT NULL,
	FOREIGN KEY (roomID) REFERENCES Properties.tblStorageRoom (roomID) ON DELETE NO ACTION ON UPDATE NO ACTION,
);

CREATE TABLE Properties.tblShelfRow (
	shelfRow VARCHAR(2) PRIMARY KEY NOT NULL,
	FOREIGN KEY (roomID) REFERENCES Properties.tblStorageRoom (roomID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

